---
- name: Create virtualhosts
  template:
    src: virtualhost.j2
    dest: "/etc/nginx/conf.d/{{ vh }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ root_directory }}"
  loop_control:
    loop_var: vh
  register: vh_tmpl

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
  when: vh_tmpl.changed
