---
webservers:
  hosts:
    web1.lab:
      ansible_host: 192.168.1.17

infra:
  vars:
    ansible_user: runner
    ansible_python_interpreter: "/usr/bin/python2"
    ansible_connection: "ssh"
    ansible_ssh_private_key_file: "~/.ssh/runner"
    ansible_become: true
    ansible_become_user: "root"
  children:
    webservers:

all:
  children:
    infra: